x-base-service: &base-service
    env_file: ./.env
    restart: on-failure

services:
    bot:
        <<: *base-service
        build:
            context: .
            dockerfile: ./docker/bot/Dockerfile
        depends_on:
            - adminpanel

    adminpanel:
        <<: *base-service
        build:
            context: .
            dockerfile: ./docker/adminpanel/Dockerfile
        environment:
            - APP_HOST=adminpanel
            - APP_PORT=8000
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - postgres
            - redis
        volumes:
            - ./adminpanel/src:/src
        ports:
            - "8000:8000"

    celery:
        <<: *base-service
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        environment:
            - APP_HOST=adminpanel
            - APP_PORT=8000
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - postgres
            - redis
        volumes:
            - ./adminpanel/src:/src
    
    celery_beat:
        <<: *base-service
        build:
            context: .
            dockerfile: ./docker/celery_beat/Dockerfile
        environment:
            - APP_HOST=adminpanel
            - APP_PORT=8000
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - CELERY_BEAT_SCHEDULER=django_celery_beat.schedulers:DatabaseScheduler
            - CELERY_BROKER_URL=redis://redis:6379
            - CELERY_RESULT_BACKEND=redis://redis:6379
        depends_on:
            - postgres
            - redis
            - celery
        volumes:
            - ./adminpanel/src:/src

    nginx:
        <<: *base-service
        image: nginx:1.21.6-alpine
        environment:
            - APP_HOST=adminpanel
            - APP_LISTEN_PORT=${APP_NGINX_PORT}
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/templates:/etc/nginx/templates
            - static_value:/var/html/static/
        ports:
            - ${APP_NGINX_PORT}:${APP_NGINX_PORT}
        depends_on:
            - adminpanel

    postgres:
        <<: *base-service
        image: postgres:14.3-alpine
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        <<: *base-service
        image: redis:7-alpine
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - redis_data:/data

volumes:
    pgdata:
    redis_data:
    static_value: