services:
    bot:
        build:
            context: .
            dockerfile: ./docker/bot/Dockerfile
        restart: on-failure
        env_file: ./.env
        depends_on:
            - webapi

    webapi:
        build:
            context: .
            dockerfile: ./docker/webapi/Dockerfile
        restart: on-failure
        env_file: ./.env
        environment:
            - FLASK_APP=manage.py
            - APP_HOST=0.0.0.0
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - postgres
            - redis

    nginx:
        image: nginx:1.21.6-alpine
        restart: on-failure
        env_file: ./.env
        environment:
            - APP_HOST=webapi
            - APP_LISTEN_PORT=${APP_NGINX_PORT}
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/templates:/etc/nginx/templates:ro
        ports:
            - ${APP_NGINX_PORT}:${APP_NGINX_PORT}
        depends_on:
            - webapi

    postgres:
        image: postgres:14.3-alpine
        restart: on-failure
        env_file: ./.env
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        restart: on-failure
        env_file: ./.env
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - redis_data:/data

volumes:
    pgdata:
    redis_data:
